title: FabrizioSulcaR|Blog
description: > # this means to ignore newlines until "baseurl:"
  Este es el espacio en el que soltaré mis recuerdos más intimos. También soltaré algunas reflexiones y aprendizajes. Espero que disfruten su estadía por acá.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://fabriziosulcar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: FabrizioSulcaR #if your site has a twitter account, enter it here

# Author Settings
author: Fabrizio Sulca Reynaldo
author-img: david-freeman.jpg # add your photo
about-author: Estudiante de Economía UP Interesado en automatización, ciencia de datos, políticas públicas y otras cosas de nerds. Siempre con ganas de aprender. # add description
social-twitter: FabrizioSulcaR # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: FabrizioSulcaR # add your Github handle
social-linkedin: Fabrizio Sulca Reynaldo # add your Linkedin handle
social-email: fr.sulcar@alum.up.edu.pe # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
